config/routes.rb
Documents::Application.routes.draw do
    root "documents#index"
    get "access/:acess_code" => "acess_codes#index"
    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" }
    else
      devise_for :users
    end
    resources :documents
    post "documents/:id/sign" => "documents#sign"
    get 'clients/:id/prepare_documents' => 'clients#prepare_docs'
    get 'clients/:id/:access_code' => "clients#auth"
    post 'clients/access' => "clients#access_create"
    get 'clients/access' => "clients#access"
    get 'clients/codes' => "clients#codes"
    resources :clients
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :documents
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :phone
  validates :email, confirmation: true
  validates :email, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                                    message: "Must be email user @ domain . tld" }
  has_many :acess_codes

  def avatar_url()
    default_url = "/assets/guest.png"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! , only: [:index,:edit,:update,:destroy,:new,:create,:codes,:access,:access_create]
  before_action :auth_code, only: [:show,:prepare_docs]
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @documents = @client.documents
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  #GET /clients/access
  def access
    @clients = Client.all
    @access = AcessCode.new
  end

  #GET /client/1/:code
  def auth
    if params[:id] and params[:access_code]
      @access = AcessCode.find_by(code: params[:access_code])
      @client = Client.find(params[:id])
      if @access and @client and @client.id == @access.client.id
        session[:access_code] = @access.code
        redirect_to client_path, :id => @client.id
      else
        redirect_to "https://www.google.com"
      end
    else
      redirect_to "https://www.google.com"
    end
  end

  def access_create
    @access = AcessCode.new
    @access.code=SecureRandom.uuid
    @access.expiry = 10.days.from_now
    @access.client_id = params[:acess_code][:client_id]
    @access.save
    redirect_to clients_codes_path
  end

  def codes
    @clients = Client.all
    @access = AcessCode.all
  end

  #GET /clients/1/prepare_docs
  def prepare_docs
    @client = Client.find(params[:id])
    @documents = @client.documents
    @documents.each do |document|
      @document = document
      pdf = WickedPdf.new.pdf_from_string(render_to_string('documents/document', :layout => 'pdf'))
      url = "/pdfs/document-#{@document.id}.pdf"
      save_path = "public/#{url}"
      File.open(save_path, 'wb') do |file|
        file << pdf
      end
      @document.file_url = url
      @document.save
    end
    render 'documents/items',:layout => false
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email,:email_confirmation,:phone)
    end

    def auth_code
      if session[:access_code]
        @access = AcessCode.find_by(code: session[:access_code])
        if @access.client.id == params[:id].to_i
          return true
        end
      else
        redirect_to "https://www.google.com"
      end
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="ui
  <% if @client.errors.any? %>error
  <% end %> form segment">
  <%= form_for(@client) do |f| %>
      <% if @client.errors.any? %>
          <div class="ui error message">
            <div class="header"><%= pluralize(@client.errors.count, "error") %> prohibited this document from being
              saved:
            </div>
            <ul>
              <% @client.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :email_confirmation %>
        <%= f.text_field :email_confirmation %>
      </div>
      <div class="field">
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>
      <button class="ui button teal submit">
        Create
      </button>
  <% end %>
</div>

app/views/clients/access.html.erb
<h4 class="ui inverted teal block header">Create Access Code</h4>
<%= form_tag  do |f| %>
<div class="ui form segment">
  <div class="field">
    <%= collection_select(:acess_code, :client_id, Client.all, :id, :name) %>
  </div>
  <button type="submit" class="ui blue submit button">Create</button>
</div>
<% end %>
<%= link_to 'Back', documents_path %>

app/views/clients/codes.html.erb
<div class="ui piled feed segment">
  <h2 class="ui header">
    Access Codes
  </h2>
  <% @access.each do |a|%>
  <div class="event">
    <div class="label">
      <i class="circular code icon"></i>
    </div>
    <div class="content">
      /clients/<%= a.client.id %>/<%= a.code %>
    </div>
  </div>
  <% end %>
    </div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<h4 class="ui inverted teal block header">
  <%= @client.name %>: Documents For Acceptance
</h4>
<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <div class="ui vertical steps">
        <div class="ui step active">
          Welcome
        </div>
        <% @documents.each_with_index do |doc, i| %>
            <div class="ui <%if doc.title.length > 20 %>two line<% end %> step" data-step="<%= i %>">
              <%= doc.title %>
            </div>
        <% end %>
        <div class="ui step">
          Finished
        </div>
      </div>
    </div>
  </div>
  <div class="twelve wide column">
    <div class="ui segment">
      <div class="ui pointing document-tab menu" data-client="<%= @client.id %>">
        <a class="active red item" data-tab="welcome">Welcome</a>
        <% @documents.each_with_index do |doc, i| %>
            <a class="blue item" data-tab="doc-<%= i %>"><%= truncate(doc.title, length: 15) %></a>
        <% end %>
        <a class="green item" data-tab="finished">Finished</a>
      </div>
      <div class="tabs">
        <div class="ui active tab segment" data-tab="welcome">
          <h1>Welcome</h1>

          <p>Welcome to Farmington Web Design's Online Project Confirmation tool.</p>

          <p> We <b>created</b> this beautiful tool to make it easy for our clients to accept our project scopes,
            designs
            and terms without having to hassle with scanners and email and other time wasting things.</p>
          <button class="ui right labeled icon button next-button"><i class="right arrow icon"></i> Next</button>
        </div>
        <% @documents.each_with_index do |doc, i| %>
            <div class="ui tab segment document" data-tab="doc-<%= i %>">
              <form class="ui form document-sign-form" data-docid="<%= doc.id %>" data-name="<%= i %>" method="post">
                <div class="quicksigndoc doc-<%= i %>">
                  <label>Print Name:</label>
                  <%= @client.name %>,
                  <p>The above person certifies by entering their name and signing that they understand all of the
                    terms, limitations and other binding word contained herein.</p>
                </div>
                <div class="ui segment">
                  <label>Sign Name</label>

                  <div class="quicksign" data-name="<%= i %>" data-pentype="thin" data-color="#03963D" data-content="You have to sign the document.">
                    <img data-name="<%= i %>" src="/images/qsback.png"/></div>
                </div>
                <i class="ui popup"></i>
                <button class="ui right labeled icon button" type="submit">
                  <i class="right arrow icon"></i>
                  Accept
                </button>
              </form>
              <%= raw doc.rendered_document %>
            </div>
        <% end %>
        <div class="ui tab segment" data-tab="finished">
          <h1>All Done</h1>
          <p>Now that wasn't so bad, now was it. Didn't hurt a bit.</p>
          Please Rate Your Experience.
          <div class="ui huge star rating">
            <i class="icon"></i>
            <i class="icon"></i>
            <i class="icon"></i>
            <i class="icon"></i>
            <i class="icon"></i>
          </div>

          <div class="ui items download-docs">
            <div class="item">
            </div>
            <div class="ui active inverted dimmer">
              <div class="ui text loader">Creating PDFs...</div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  </div>
  <div id="quicksignwrap">
    <canvas id="quicksign"></canvas>
  </div>