config/routes.rb
Documents::Application.routes.draw do
    root "documents#index"
    get "access/:acess_code" => "acess_codes#index"
    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" }
    else
      devise_for :users
    end
    resources :documents
    post "documents/:id/sign" => "documents#sign"
    get 'clients/:id/prepare_documents' => 'clients#prepare_docs'
    get 'clients/:id/:access_code' => "clients#auth"
    post 'clients/access' => "clients#access_create"
    get 'clients/access' => "clients#access"
    get 'clients/codes' => "clients#codes"
    resources :clients
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :client

  validates_presence_of :title
  markdownize! :document

  def has_client?
    return self.client
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:index,:new,:create,:update,:destroy]
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents/1/sign.json
  def sign
    @document = Document.find(params[:id])
    if(@document)
      image = params[:image_data]
      decoded_file = Base64.decode64(image['data:image/png;base64,'.length .. -1])
      path ="public/signs/document-#{@document.id}.png"
      begin
        File.open(path, 'wb') do|f|
          f.write(decoded_file)
        end
      rescue Exception => e
        render :json => e.message.as_json
        return
      end
      @document.seen_from_ip = request.remote_ip
      @document.client_seen = true
      @document.signed_or_accepted = true
      if @document.save()
        render :json => {:image => path.as_json}
      end
    else
      render :json => "Doc Not Found".as_json
    end
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :client_id,:document)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<div class="ui
  <% if @document.errors.any? %>error
  <% end %> form segment">
  <%= form_for(@document) do |f| %>
      <% if @document.errors.any? %>
          <div class="ui error message">
            <div class="header"><%= pluralize(@document.errors.count, "error") %> prohibited this document from being
              saved:
            </div>
            <ul>
              <% @document.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :document %>
        <%= f.text_area :document %>
      </div>
       <div class="field">
         <%= collection_select(:document, :client_id, Client.all, :id, :name) %>
       </div>
      <button class="ui button teal submit">
       Create
      </button>
  <% end %>
</div>

app/views/documents/document.html.erb
<label>Print Name:</label> <%= @client.name %>,
      <p>The above person certifies by entering their name and signing that they understand all of the
        terms, limitations and other binding word contained herein.</p>
<label>Sign Name</label>
<br>
<%= wicked_pdf_image_tag "/signs/document-#{@document.id}.png"%>
<h3>Signed by <%= @client.name %> on <%= @document.updated_at.strftime("%b %e, %l:%M %p") %></h3>
<%= raw @document.rendered_document %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h4 class="ui inverted teal block header">
  Documents, legality with style
</h4>
<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <div class="ui vertical menu">
        <a class="active teal item">
          Signed
          <div class="ui teal label"><%= @signed %>0</div>
        </a>
        <a class="item" href="">
          Not Signed
          <div class="ui label"><%= @not_signed %>0</div>
        </a>
        <a class="item" href="<%= url_for new_document_path %>">
          New Document
        </a>
        <a class="item" href="<%= url_for new_client_path %>">
          New Client
        </a>
        <a class="item" href="<%= url_for clients_url %>">
          Clients
        </a>
        <a class="item" href="<%= url_for clients_codes_url %>">
          Access Codes
        </a>
        <a class="item" href="<%= url_for clients_access_url %>">
          Create Access Code
        </a>

      </div>
    </div>
  </div>
  <div class="twelve wide column">
    <div class="ui segment">
      <div class="ui animated list">
        <% @documents.each do |document| %>
            <div class="item">
                <img class="ui avatar image circular" src="/images/guest.png">
              <div class="content">
                <div class="header"><a href="<%= edit_document_path(document) %>"><%= document.title %></a></div>
                <%= document.updated_at.strftime("%b %e, %l:%M %p") %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/documents/items.html.erb
<% @documents.each_with_index do |doc, i| %>
    <div class="item">
      <div class="content">
        <div class="name"><%= doc.title %></div>
        <p class="description"><a href="<%= doc.file_url %>" class="button">Download</a> </p>
      </div>
    </div>
<% end %>

app/views/documents/new.html.erb
<h1>Create Document  <%= link_to 'Back', documents_path %></h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>